config/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.contrib.auth.decorators import login_required
from django.urls import path, include
from django.views.generic import RedirectView
from django_pydenticon.views import image as pydenticon_image

urlpatterns = [
    path('admin/', admin.site.urls),
    path('accounts/', include('accounts.urls')),
    path('identicon/image/<path:data>/', pydenticon_image,name='pydenticon_image'),
    path('instagram/', include('instagram.urls')),
    path('', login_required(RedirectView.as_view(pattern_name='instagram:index')), name='root'),
]

if settings.DEBUG:
    import debug_toolbar
    urlpatterns += [
        path('__debug__/', include(debug_toolbar.urls))
    ]
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

instagram/urls.py
from django.urls import path, re_path
from django.contrib.auth.validators import UnicodeUsernameValidator
from . import views


app_name = 'instagram'

urlpatterns = [
    path('', views.index, name='index'),
    path('post/new/', views.post_new, name='post_new'),
    path('post/<int:pk>/', views.post_detail, name='post_detail'),
    path('post/<int:pk>/like/', views.post_like, name='post_like'),
    path('post/<int:pk>/unlike/', views.post_unlike, name='post_unlike'),
    path('post/<int:post_pk>/comment/new/', views.comment_new, name='comment_new'),
    re_path(r'^(?P<username>[\w.@+-]+)/$', views.user_page, name='user_page'),
]

instagram/models.py
import re
from tkinter import CASCADE
from django.conf import settings
from django.db import models
from django.urls import reverse


class BaseModel(models.Model):
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)

    class Meta:
        abstract = True

class Post(BaseModel):
    author = models.ForeignKey(settings.AUTH_USER_MODEL, related_name='my_post_set', on_delete=models.CASCADE)
    photo = models.ImageField(upload_to="instagram/post/%Y/%m/%d")
    caption = models.TextField(max_length=500)
    tag_set = models.ManyToManyField('Tag', blank=True)
    location = models.CharField(max_length=100)
    like_user_set = models.ManyToManyField(settings.AUTH_USER_MODEL, blank=True, related_name='like_post_set')


    def __str__(self):
        return self.caption

    def extract_tag_list(self):
        tag_name_list = re.findall(r"#([a-zA-Z\dㄱ-힣]+)", self.caption)
        tag_list = []
        for tag_name in tag_name_list:
            tag, _ = Tag.objects.get_or_create(name=tag_name)
            tag_list.append(tag)
        
        return tag_list

    def get_absolute_url(self):
        return reverse("instagram:post_detail", kwargs={"pk": self.pk})

    def is_like_user(self, user):
        return self.like_user_set.filter(pk=user.pk).exists()
    
    class Meta:
        ordering = ['-id']


class Comment(BaseModel):
    author = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE)
    post = models.ForeignKey(Post, on_delete=models.CASCADE)
    message = models.TextField()

    class Meta:
        ordering = ['-id']


class Tag(models.Model):
    name = models.CharField(max_length=50, unique=True)

    def __str__(self):
        return self.name

instagram/forms.py
from django import forms
from .models import Post, Comment


class PostForm(forms.ModelForm):
    class Meta:
        model = Post
        fields = ['photo', 'caption', 'location']
        widgets = {
            'caption': forms.Textarea,
        }


class CommentForm(forms.ModelForm):
    class Meta:
        model = Comment
        fields = ['message']
        widgets = {
            "message": forms.Textarea(attrs={"rows": 3}),
        }

instagram/views.py
from datetime import timedelta
from django.contrib import messages
from django.contrib.auth import get_user_model
from django.contrib.auth.decorators import login_required
from django.db.models import Q
from django.shortcuts import render, redirect, get_object_or_404
from django.utils import timezone
from .forms import PostForm, CommentForm
from .models import Post


@login_required
def index(request):
    timesince = timezone.now() - timedelta(days=3) # 최근 시간 - 3일의 시간을 뺀 날짜

    post_list = Post.objects.all().filter(Q(author__in=request.user.following_set.all()) | Q(author=request.user)).filter(created_at__gte=timesince)
    suggested_user_list = get_user_model().objects.all().exclude(pk=request.user.pk).exclude(pk__in=request.user.following_set.all())[:3]
    
    comment_form = CommentForm()

    return render(request, "instagram/index.html", {
        'suggested_user_list': suggested_user_list,
        'post_list': post_list,
        'comment_form': comment_form,
    })


@login_required
def post_new(request):
    if request.method == 'POST':
        form = PostForm(request.POST, request.FILES)

        if form.is_valid():
            post = form.save(commit=False)
            post.author = request.user
            post.save()
            post.tag_set.add(*post.extract_tag_list())
            messages.success(request, "포스팅을 저장하였습니다.")

            return redirect(post) # TODO : get)absolute_url 활용

    else:
        form = PostForm()

    return render(request, "instagram/post_form.html", {
        'form' : form,
    })


def post_detail(request, pk):
    post = get_object_or_404(Post, pk=pk)
    comment_form = CommentForm()

    return render(request, "instagram/post_detail.html", {
        "post": post,
        "comment_form": comment_form,
    })


@login_required
def post_like(request, pk):
    post = get_object_or_404(Post, pk=pk)
    post.like_user_set.add(request.user)
    
    messages.success(request, "포스팅을 좋아합니다.")
    redirect_url = request.META.get("HTTP_REFERER", "root")

    return redirect(redirect_url)


def post_unlike(request, pk):
    post = get_object_or_404(Post, pk=pk)
    post.like_user_set.remove(request.user)

    messages.success(request, "포스팅의 좋아요를 취소합니다.")
    redirect_url = request.META.get("HTTP_REFERER", "root")

    return redirect(redirect_url)


@login_required
def comment_new(request, post_pk):
    post = get_object_or_404(Post, pk=post_pk)

    if request.method == 'POST':
        form = CommentForm(request.POST, request.FILES)
        
        if form.is_valid():
            comment = form.save(commit=False)
            comment.post = post
            comment.author = request.user
            comment.save()

            if request.META.get('HTTP_X_REQUESTED_WITH') == 'XMLHttpRequest':
                return render(request, 'instagram/_comment.html', {
                    'comment': comment,
                })


            return redirect(comment.post)
    else:
        form = CommentForm()
    
    return render(request, "instagram/comment_form.html",{
        "form": form,
    })



def user_page(request, username):
    page_user = get_object_or_404(get_user_model(), username=username, is_active=True)

    # User Follow
    if request.user.is_authenticated:
        is_follow = request.user.following_set.filter(pk=page_user.pk).exists()
    else:
        is_follow = False

    # Post
    post_list = Post.objects.filter(author=page_user)
    post_list_count = post_list.count() # 실제 데이터베스에 count 쿼리를 던지게 된다.

    return render(request, "instagram/user_page.html", {
        "page_user": page_user,
        "post_list": post_list,
        "post_list_count": post_list_count,
        "is_follow": is_follow,
    })

instagram/templates/instagram/_comment.html
{% load humanize %}

<div class="comment">
    <a href="{% url 'instagram:user_page' comment.author %}" style="color: inherit; text-decoration: none;"><strong>{{ comment.author }}</strong></a>
    {{ comment.message }}
    <small>{{ comment.created_at|naturaltime }}</small>
</div>

instagram/templates/instagram/_post_card.html
{% load bootstrap4 humanize instagram_tags %}

<div class="card">
    <div class="card-header">
        <img src="{{ post.author.avatar_url }}" style="width: 32px; height: 32px;"/>
        <a href="{% url 'instagram:user_page' post.author.username %}" style="color: inherit; text-decoration: none;">
            {{ post.author.name }}
        </a>
    </div>
    <div class="card-body">
        <img src = "{{ post.photo.url }}" style="width:100%;" />

        <div>
            {% if post|is_like_user:user %}
                <a href="{% url 'instagram:post_unlike' post.pk %}" style="color: inherit;">
                    <i class="fa fa-heart"></i>
                </a>
            {% else %}
                <a href="{% url 'instagram:post_like' post.pk %}" style="color: inherit;">
                    <i class="fa fa-heart-o"></i>
                </a>
            {% endif %}
        </div>

        <div>
            {% for tag in post.tag_set.all %}
                <span class="badge bg-primary mt-2">
                    #{{ tag.name }}
                </span>
            {% endfor%}
        </div>

        <div id="post-{{ post.pk }}-comment-list" class="comment-list mt-3 mb-3">
            {% for comment in post.comment_set.all %}
                {% include 'instagram/_comment.html' %}
            {% endfor %}
        </div>

        <div>
            <a href="{{ post.get_absolute_url }}" style="color: inherit; text-decoration: none;" class="text-muted">
                <small>{{ post.created_at|naturaltime }}</small>
            </a>
        </div>
    </div>
    <div class="card-footer">
        {% comment %} <a href="{% url 'instagram:comment_new' post.pk %}" style="color: inherit; text-decoration: none;">댓글 쓰기</a> {% endcomment %}
        <form id="post-{{ post.pk }}-comment-form" action="{% url 'instagram:comment_new' post.pk %}" method="POST">
            {% csrf_token %}
            {% bootstrap_form comment_form %}
            <div class="d-grid gap-2">
                <input type="submit" value="댓글 쓰기" class="btn btn-primary mt-3">
            </div>
        </form>

        <div id="server-response-{{ post.pk }}"></div>

        <script>
            $(function(){
                var form_id = "post-{{ post.pk }}-comment-form";
                $("#" + form_id).submit(function(e) {
                    e.preventDefault();

                    var options = {
                        success: function(responseText, statusText, xhr, $form){
                            console.group("ajaxSubmit response");
                            console.log(responseText);
                            console.log(statusText);
                            console.log(xhr);
                            console.log($form);
                            console.groupEnd();

                            $("#post-{{ post.pk }}-comment-list").prepend(responseText);
                        }
                    };
                    $(this).ajaxSubmit(options);
                });
                console.log("document ready.")
            });
        </script>
    </div>
</div>

instagram/templates/instagram/comment_form.html
{% extends 'instagram/layout.html' %}

{% block content %}
    <div class="container">
        <div class="row">
            <div class="col-sm-6 offset-sm-3">
                {% include "_form.html" with form_title="댓글 쓰기" submit_label="댓글 쓰기" %}
            </div>
        </div>
    </div>
{% endblock content %}

instagram/templates/instagram/index.html
{% extends 'instagram/layout.html' %}

{% block content %}
    <div class="container">
        <div class="row mb-3">
            <div class="col-sm-12">
                <a href="{% url 'instagram:post_new' %}" class="btn btn-primary">새 글 작성하기</a>
            </div>
        </div>
        <div class="row">
            <div class="col-sm-8">
                {% for post in post_list %}
                <div class="mb-3">
                    {% include "instagram/_post_card.html" %}
                </div>
                {% endfor %}
            </div>
            <div class="col-sm-4">
                {% include 'instagram/timeline_sidebar.html' %}
            </div>
        </div>
    </div>
{% endblock content %}

instagram/templates/instagram/layout.html
{% extends 'layout.html' %}

instagram/templates/instagram/post_detail.html
{% extends "instagram/layout.html" %}

{% block content %}
    <div class="container">
        <div class="row">
            <div class="col-sm-12">
                {% include "instagram/_post_card.html" %}
            </div>
        </div>
    </div>
{% endblock content %}

instagram/templates/instagram/post_form.html
{% extends 'instagram/layout.html' %}

{% block content %}
    <div class="container">
        <div class="row">
            <div class="col-sm-6 offset-sm-3">
                {% include "_form.html" with form_title="새 글 쓰기" submit_label="새 글 쓰기" %}
            </div>
        </div>
    </div>
{% endblock content %}

instagram/templates/instagram/timeline_sidebar.html
<div class="d-flex p-2">
    <div class="me-2">
        <img src="{{ user.avatar_url }}" alt="user_avatar" style="width: 48px; height: 48px;" class="rounded-circle">
    </div>
    <div>
        {{ user.username }}<br/>
        <small class="text-muted">{{ user.name }}</small>
    </div>
</div>

<div class="card mb-3">
    <div class="card-header text-muted">
        Stories
    </div>
    <div class="card-body text-muted">
        Stories form people you follow will show up here.
    </div>
</div>

<div class="card mb-3">
    <div class="card-header text-muted">
        Suggestions for you
    </div>
    <div class="card-body text-muted">
        {% for suggested_user in suggested_user_list %}
            {% include 'instagram/timeline_sidebar_user_follow.html' %}
        {% empty %}
            추천 친구가 없습니다.
        {% endfor %}
    </div>
</div>

instagram/templates/instagram/timeline_sidebar_user_follow.html
<div class="d-flex mb-1">
    <div class="me-2">
        <img src="{{ suggested_user.avatar_url }}" alt="freind_user_avatar" style="width: 32px; height: 32px;" class="rounded-circle"/>
    </div>
    <div class="">
        <a href="{% url 'instagram:user_page' suggested_user.username %}" style="color: inherit; text-decoration: none;">
            {{ suggested_user.username }}
        </a>
    </div>
    <div class="ms-auto">
        <a href="{% url "user_follow" suggested_user.username %}" style="color: inherit; text-decoration: none;">Follow</a>
    </div>
</div>

instagram/templates/instagram/user_page.html
{% extends 'instagram/layout.html' %}
{% load thumbnail%}

{% block content %}
    <div class="container">
        <div class="row pt-5 pb-5">
            <div class="col-sm-3" style="text-align: center;">
                <img src="{{ page_user.avatar_url }}" alt="avatar" class="rounded-circle" style="width: 160px;">
            </div>
            <div class="col-sm-9">
                {{ page_user.username }}
                <a href="{% url 'profile_edit' %}" class="btn btn-secondary btn-sm">Edit Profile</a>
                {% if is_follow %}
                    <a href="{% url "user_unfollow" page_user.username %}">UnFollow</a>
                {% else %}
                    <a href="{% url "user_follow" page_user.username %}">Follow</a>
                {% endif %}
                <hr/>
                {{ post_list_count }} posts, 0 followers, 0 following
                <hr/>
                {{ page_user.name }}
            </div>
        </div>
        <div class="row mt-3" >
            {% for post in post_list%}
                <div class="col-sm-4 mb-4">
                    <img src="{% thumbnail post.photo 256x256 crop %}" alt="{{ post.caption }}" sytle="width: 100%;"/>
                </div>
            {% endfor %}
        </div>
    </div>
{% endblock content %}